# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nodejsprueba
# "service" is the name of this project. This will also be added to your AWS resource names.
service: majolero

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.12

functions:
  christmassTree:
    handler: handler.christmassTree
    events:
      - http:
          path: /
          method: get

  
